version: '3'

services:
  fe-react:
    container_name: fe-react
    ports:
      - 3003:3003
    build: ./fe
    env_file:
      - ./fe/.env
    environment:
      - REACT_APP_API_URL=${REACT_APP_API_URL:-http://167.71.200.72:3002}
      - PORT=${PORT:-3003}
    restart: unless-stopped

  be-nodejs:
    container_name: be-nodejs
    ports:
      - 3002:3002
    build: ./be
    env_file:
      - ./be/.env
    environment:
      - PORT=${BE_PORT:-3002}
      - DB_USER=${DB_USER:-root}
      - DB_NAME=${DB_NAME:-social_demo}
    restart: unless-stopped