# name: # workflow name
# on: # event to run (trigger)
# env: # Environment variable (optional)
# permissions: # GitHub Token permission (optional)
# # actions: read | write | none
# # checks: read | write | none
# # contents: read | write | none
# # deployments: read | write | none
# # id-token: write | none
# # issues: read | write | none
# # discussions: read | write | none
# # packages: read | write | none
# # pages: read | write | none
# # pull-requests: read | write | none
# # repository-projects: read | write | none
# # security-events: read | write | none
# # statuses: read | write | none
# # workflows: read | write | none
# jobs: # Job list
#  build: (hệ điều hành github hỗ trợ)
#   runs-on: ubuntu-latest | windows-latest | macos-latest
#  needs: chờ job trước chạy xong cái job sau mới chạy
#  steps:
#   run: lệnh CLI
#   uses: dùng một action có sẵn trên marketplace
#   with: truyền input
#   env: khai báo biến
# Truy cập biến:
#   github: lấy thông tin của repo, actor, ref, sha, ...
#   vars: lấy nội dung variable khai báo trong setting repo
#   secrets: lấy nội dung secret khai báo trong setting repo
#   steps: output từ trong step đó
#   needs: output từ các jobs phía trước

name: demo-workflow
on:
 workflow_dispatch:
  # version:
  #   type: string
  #   require: true

jobs:
  run-demo: 
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Run demo
        run: |
          echo "hello world"
          echo "Repository: ${{ github.repository }}"
          echo "Actor: ${{ github.actor }}"
