name: demo-workflow
on:
  push:
    branches: [fe-nginx-demo, main]

jobs:
  job0:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "hello world"
  job1:
    runs-on: ubuntu-latest
    needs: [job0]
    steps:
      - run: |
          echo "hello world"
  job2:
    runs-on: ubuntu-latest
    needs: [job0]
    steps:
      - run: |
          echo "hello world"
  job3:
    runs-on: ubuntu-latest
    needs: [job2]
    steps:
      - run: |
          echo "hello world"

